# Generated by Django 5.1.3 on 2024-12-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_powerpointfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerPointFile',
        ),
    ]
